* Startpunkt digitaler Output
Blink Beispiel: File $\rightarrow$ Examples $\rightarrow$ Basics $\rightarrow$ Blink

#+NAME: Blink
#+INCLUDE: "code/blink.c" src C

* setup
~pinmode(pin, modus)~ wählt für den Pin mit Nummer ~pin~ eine von drei
Betriebsarten:

- ~OUTPUT~: wird für Ausgabe verwendet, z.B. um LEDs zu schalten oder
  mit anderen Microcontrollern zu sprechen.
- ~INPUT~: die Spannung am Pin kann gelesen werden.
- ~INPUT_PULLUP~: wie ~INPUT~, aber der Pin wird intern auf die
  Versorgunsspannung gezogen.

* digitalWrite und Delay
~digitalWrite(pin, zustand)~ setzt bei einem auf ~OUTPUT~ gestellten Pin
die Ausgangsspannung:

- 0 Volt für ~LOW~
- 5 Volt für ~HIGH~ (oder was auch immer die aktuelle
  Versorgungsspannung ist)

~delay(ms)~ tut ~ms~ Millisekunden lang nichts.

* Andere Blink Muster
Zwei Sekunden lang an, eine halbe aus.

#+beamer: \pause

#+INCLUDE: "code/blink_pattern.c" src C

* Schnelleres Blinken
Was passiert, wenn man die Zeiten ganz niedrig setzt?
#+beamer: \pause

$\rightarrow$ Man sieht kein Blinken mehr
#+beamer: \pause

Was passiert, wenn die Zeitverhältnisse geändert werden?
#+beamer: \pause

$\rightarrow$ Dimmen
